// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkpasswordsetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbasicinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginorregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerwiththirdpartyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _third_partyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _thirdpartycallbackMw() []app.HandlerFunc {
	// your code...
	return nil
}
