// Code generated by hertz generator.

package verify

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendemallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendsmsMw() []app.HandlerFunc {
	// your code...
	return nil
}
